config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  get 'sessions/create'
  get 'sessions/destroy'
  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'repositories#index'
  resources :repositories, only: [:index, :show] do
    member do
      get 'get_commits', defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate_user
    if current_user.blank?
      redirect_to login_path
    end
  end

  def current_user
    begin
      session[:user_id].nil? ? nil : User.find(session[:user_id])
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end
end

app/controllers/repositories_controller.rb
require 'net/http'
require 'openssl'
require 'json'

class RepositoriesController < ApplicationController
  before_action :authenticate_user
  def index
    if current_user.present?
      user_name = current_user.username
      uri = URI("https://api.github.com/users/#{user_name}/repos?client_id=#{ENV['GITHUB_CLIENT_ID']}&client_secret=#{ENV['GITHUB_CLIENT_SECRET']}")
      repositories = Net::HTTP.get(uri)
      json_result = JSON.parse(repositories)
      @repo_names_with_access = json_result
    end
  end

  def show
    @repository_name = params[:id]
    @repository_description = params[:description]
    @user_name = current_user.username.to_s
    since = Time.now - 30.days
    till = Time.now
    uri = URI("https://api.github.com/repos/#{@user_name}/#{@repository_name}/commits?client_id=#{ENV['GITHUB_CLIENT_ID']}&client_secret=#{ENV['GITHUB_CLIENT_SECRET']}&since=#{since}&until=#{till}")
    commit_history = Net::HTTP.get(uri)
    json_result = JSON.parse(commit_history)
    @commit_history_array = json_result.map{|e| e["commit"]["author"]["date"]}.join(",")
  end

  def get_commits
    since = params[:startDate]
    till = params[:endDate]
    user_name = current_user.username
    repository_name = params[:id]
    uri = URI("https://api.github.com/repos/#{user_name}/#{repository_name}/commits?client_id=#{ENV['GITHUB_CLIENT_ID']}&client_secret=#{ENV['GITHUB_CLIENT_SECRET']}&since=#{since}&until=#{till}")
    commit_history = Net::HTTP.get(uri)
    json_result = JSON.parse(commit_history)
    @commit_history_array = json_result.map{|e| e["commit"]["author"]["date"]}.join(",")
    render json: json_result
  end
end

app/controllers/sessions_controller.rb
require 'net/http'
require 'openssl'
require 'json'

class SessionsController < ApplicationController
  layout false
  def new
  end

  def create
    user = User.from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to repositories_path
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmuratechAssignment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
      .axis {
        font: 10px sans-serif;
      }

      .axis path,
      .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
      }
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <% if current_user.blank? %>
          <h1>Please Sign In</h1>
          <%= link_to 'Sign In with Github', '/auth/github' %>
        <% else %>
          Welcome <%= current_user.username %>
        <div class="navbar-nav">
          <%= link_to "Sign Out", signout_path, method: :delete, class: "nav-item nav-link pull-right" %>
        </div>
        <%end%>
      </div>
    </nav>
    <%= render partial: "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/repositories/index.html.erb
<table class="table table-striped sortable css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>Repository Name</th>
      <th>Repository Description</th>
    </tr>
  </thead>
  <tbody>
    <%if @repo_names_with_access.present? %>
      <% @repo_names_with_access.each do |repo| %>
        <tr>
          <td></td>
          <td><%= link_to(repo["name"], repository_path(id: repo["name"], description: repo["description"])) %></td>
          <td><%= repo["description"] %></td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>

app/views/repositories/show.html.erb
<div class="row">
  <div class="col-xs-1" style="padding-left: 3%">
    <h2><%= @repository_name %></h2>
    <p><%= @repository_description %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-8" style="padding-left: 3%">
    <div class="row">
      <div class="col-md-3">Start date: <input type="text" id="startdate" class="datepicker"></div>
      <div class="col-md-3">End date: <input type="text" id="enddate" class="datepicker"></div>
      <div class="col-md-2">
        <button type="button" class="btn btn-primary" id="getcommits" onclick="getCommitBtn()" style="position: absolute;bottom: 0">Get commits</button>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-7 medium-7 small-12 columns" id="chart">
    <ol id="langDetails"></ol>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    var date = new Date();
    date.setMonth(date.getMonth() - 1);

    $( "#startdate" ).datepicker().datepicker("setDate", date);
    $( "#enddate" ).datepicker().datepicker("setDate", new Date());
  });
  function getCommitBtn(){
    getCommits("<%=@repository_name %>");
  }
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/" id="test">Repository list</a></li>
    </ul>
  </div>
</nav>